// TRY

try{
    console.log(a+b)
} catch(err){
    console.log(err)
    console.log('There was an Error')
    console.log('The error was saved to the error log')
}
console.log("MY PROGRAM DOES NOT STOP")